[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

build_flags =
    -std=c++17
    -Wall
    -Wextra
    -DUSE_HAL_DRIVER
    -DSTM32F103xB
    -Iinclude

monitor_speed = 115200

upload_protocol = stlink
debug_tool = stlink